/*******************************************************************************
 * Copyright (c) 2026 IBM Corporation and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package io.openliberty.tools.intellij.lsp4jakarta.it.beanvalidation;

import com.intellij.openapi.module.Module;
import com.intellij.openapi.module.ModuleUtilCore;
import com.intellij.openapi.vfs.LocalFileSystem;
import com.intellij.openapi.vfs.VfsUtilCore;
import com.intellij.openapi.vfs.VirtualFile;
import io.openliberty.tools.intellij.lsp4jakarta.it.core.BaseJakartaTest;
import io.openliberty.tools.intellij.lsp4mp4ij.psi.core.utils.IPsiUtils;
import io.openliberty.tools.intellij.lsp4mp4ij.psi.internal.core.ls.PsiUtilsLSImpl;
import org.eclipse.lsp4j.CodeAction;
import org.eclipse.lsp4j.Diagnostic;
import org.eclipse.lsp4j.DiagnosticSeverity;
import org.eclipse.lsp4j.TextEdit;
import org.eclipse.lsp4jakarta.commons.JakartaJavaCodeActionParams;
import org.eclipse.lsp4jakarta.commons.JakartaJavaDiagnosticsParams;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

import java.io.File;
import java.util.Arrays;

import static io.openliberty.tools.intellij.lsp4jakarta.it.core.JakartaForJavaAssert.*;

@RunWith(JUnit4.class)
public class ValidationMethodParamAnnotationTest extends BaseJakartaTest {

    @Test
    public void methodParamConstraintValidation() throws Exception {
        Module module = createMavenModule(new File("src/test/resources/projects/maven/jakarta-sample"));
        IPsiUtils utils = PsiUtilsLSImpl.getInstance(getProject());

        VirtualFile javaFile = LocalFileSystem.getInstance().refreshAndFindFileByPath(ModuleUtilCore.getModuleDirPath(module)
                + "/src/main/java/io/openliberty/sample/jakarta/beanvalidation/MethodParamConstraintValidation.java");
        String uri = VfsUtilCore.virtualToIoFile(javaFile).toURI().toString();

        JakartaJavaDiagnosticsParams diagnosticsParams = new JakartaJavaDiagnosticsParams();
        diagnosticsParams.setUris(Arrays.asList(uri));

        // Test diagnostics
        Diagnostic d1 = d(51, 42, 56,
                "The @Past annotation can only be used on: Date, Calendar, Instant, LocalDate, LocalDateTime, LocalTime, MonthDay, OffsetDateTime, OffsetTime, Year, YearMonth, ZonedDateTime, HijrahDate, JapaneseDate, JapaneseDate, MinguoDate and ThaiBuddhistDate type parameters.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.Past");
        Diagnostic d2 = d(51, 77, 81,
                "The @Positive annotation can only be used on \n- BigDecimal \n- BigInteger\n- byte, short, int, long, float, double (and their respective wrappers) \n type parameters.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.Positive");
        Diagnostic d3 = d(52, 30, 46,
                "This annotation can only be used on parameters that have CharSequence, Collection, Array or Map as a parameter type.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.NotEmpty");

        Diagnostic d4 = d(57, 39, 46,
                "The @Negative annotation can only be used on \n- BigDecimal \n- BigInteger\n- byte, short, int, long, float, double (and their respective wrappers) \n type parameters.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.Negative");

        Diagnostic d5 = d(57, 66, 78,
                "The @NotBlank annotation can only be used on String and CharSequence type parameters.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.NotBlank");

        Diagnostic d6 = d(58, 34, 44,
                "The @Pattern annotation can only be used on String and CharSequence type parameters.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.Pattern");

        Diagnostic d7 = d(63, 68, 69,
                "The @Digits annotation can only be used on: \n- BigDecimal \n- BigInteger \n- CharSequence\n- byte, short, int, long (and their respective wrappers) \n type parameters.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.Digits");

        Diagnostic d8 = d(63, 86, 98,
                "The @Email annotation can only be used on String and CharSequence type parameters.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.Email");

        Diagnostic d9 = d(64, 28, 42,
                "The @FutureOrPresent annotation can only be used on: Date, Calendar, Instant, LocalDate, LocalDateTime, LocalTime, MonthDay, OffsetDateTime, OffsetTime, Year, YearMonth, ZonedDateTime, HijrahDate, JapaneseDate, JapaneseDate, MinguoDate and ThaiBuddhistDate type parameters.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.FutureOrPresent");

        Diagnostic d10 = d(69, 41, 42,
                "This annotation can only be used on parameters that have CharSequence, Collection, Array or Map as a parameter type.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.Size");

        Diagnostic d11 = d(69, 63, 64,
                "The @AssertTrue annotation can only be used on boolean and Boolean type parameters.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.AssertTrue");

        Diagnostic d12 = d(69, 93, 103,
                "The @DecimalMax annotation can only be used on: \n- BigDecimal \n- BigInteger \n- CharSequence\n- byte, short, int, long (and their respective wrappers) \n type parameters.",
                DiagnosticSeverity.Error, "jakarta-bean-validation", "FixTypeOfElement",
                "jakarta.validation.constraints.DecimalMax");

        assertJavaDiagnostics(diagnosticsParams, utils, d1, d2, d3, d4, d5, d6, d7, d8,
                d9, d10, d11, d12);

        String newText1 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth( double theGoodOldDays, @Positive String[] area,\n\t\t\t@NotEmpty ValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool(@Negative boolean subZero, @NotBlank boolean saysomething,\n\t\t\t@Pattern(regexp = \"\") Calendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo(@Digits(fraction = 0, integer = 0) boolean x, @Email Integer emailAddress,\n\t\t\t@FutureOrPresent boolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary(@Size double x, @AssertTrue String s, @DecimalMax(\"30.0\") String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams1 = createCodeActionParams(uri, d1);
        TextEdit te1 = te(0, 0, 73, 1, newText1);
        CodeAction ca1 = ca(uri, "Remove constraint annotation Past from element", d1, te1);
        assertJavaCodeAction(codeActionParams1, utils, ca1);

        String newText2 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth(@Past double theGoodOldDays, String[] area,\n\t\t\t@NotEmpty ValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool(@Negative boolean subZero, @NotBlank boolean saysomething,\n\t\t\t@Pattern(regexp = \"\") Calendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo(@Digits(fraction = 0, integer = 0) boolean x, @Email Integer emailAddress,\n\t\t\t@FutureOrPresent boolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary(@Size double x, @AssertTrue String s, @DecimalMax(\"30.0\") String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams2 = createCodeActionParams(uri, d2);
        TextEdit te2 = te(0, 0, 73, 1, newText2);
        CodeAction ca2 = ca(uri, "Remove constraint annotation Positive from element", d2, te2);
        assertJavaCodeAction(codeActionParams2, utils, ca2);

        String newText3 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth(@Past double theGoodOldDays, @Positive String[] area,\n\t\t\tValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool(@Negative boolean subZero, @NotBlank boolean saysomething,\n\t\t\t@Pattern(regexp = \"\") Calendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo(@Digits(fraction = 0, integer = 0) boolean x, @Email Integer emailAddress,\n\t\t\t@FutureOrPresent boolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary(@Size double x, @AssertTrue String s, @DecimalMax(\"30.0\") String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams3 = createCodeActionParams(uri, d3);
        TextEdit te3 = te(0, 0, 73, 1, newText3);
        CodeAction ca3 = ca(uri, "Remove constraint annotation NotEmpty from element", d3, te3);
        assertJavaCodeAction(codeActionParams3, utils, ca3);

        String newText4 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth(@Past double theGoodOldDays, @Positive String[] area,\n\t\t\t@NotEmpty ValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool( boolean subZero, @NotBlank boolean saysomething,\n\t\t\t@Pattern(regexp = \"\") Calendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo(@Digits(fraction = 0, integer = 0) boolean x, @Email Integer emailAddress,\n\t\t\t@FutureOrPresent boolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary(@Size double x, @AssertTrue String s, @DecimalMax(\"30.0\") String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams4 = createCodeActionParams(uri, d4);
        TextEdit te4 = te(0, 0, 73, 1, newText4);
        CodeAction ca4 = ca(uri, "Remove constraint annotation Negative from element", d4, te4);
        assertJavaCodeAction(codeActionParams4, utils, ca4);

        String newText5 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth(@Past double theGoodOldDays, @Positive String[] area,\n\t\t\t@NotEmpty ValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool(@Negative boolean subZero, boolean saysomething,\n\t\t\t@Pattern(regexp = \"\") Calendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo(@Digits(fraction = 0, integer = 0) boolean x, @Email Integer emailAddress,\n\t\t\t@FutureOrPresent boolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary(@Size double x, @AssertTrue String s, @DecimalMax(\"30.0\") String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams5 = createCodeActionParams(uri, d5);
        TextEdit te5 = te(0, 0, 73, 1, newText5);
        CodeAction ca5 = ca(uri, "Remove constraint annotation NotBlank from element", d5, te5);
        assertJavaCodeAction(codeActionParams5, utils, ca5);

        String newText6 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth(@Past double theGoodOldDays, @Positive String[] area,\n\t\t\t@NotEmpty ValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool(@Negative boolean subZero, @NotBlank boolean saysomething,\n\t\t\tCalendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo(@Digits(fraction = 0, integer = 0) boolean x, @Email Integer emailAddress,\n\t\t\t@FutureOrPresent boolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary(@Size double x, @AssertTrue String s, @DecimalMax(\"30.0\") String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams6 = createCodeActionParams(uri, d6);
        TextEdit te6 = te(0, 0, 73, 1, newText6);
        CodeAction ca6 = ca(uri, "Remove constraint annotation Pattern from element", d6, te6);
        assertJavaCodeAction(codeActionParams6, utils, ca6);

        String newText7 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth(@Past double theGoodOldDays, @Positive String[] area,\n\t\t\t@NotEmpty ValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool(@Negative boolean subZero, @NotBlank boolean saysomething,\n\t\t\t@Pattern(regexp = \"\") Calendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo( boolean x, @Email Integer emailAddress,\n\t\t\t@FutureOrPresent boolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary(@Size double x, @AssertTrue String s, @DecimalMax(\"30.0\") String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams7 = createCodeActionParams(uri, d7);
        TextEdit te7 = te(0, 0, 73, 1, newText7);
        CodeAction ca7 = ca(uri, "Remove constraint annotation Digits from element", d7, te7);
        assertJavaCodeAction(codeActionParams7, utils, ca7);

        String newText8 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth(@Past double theGoodOldDays, @Positive String[] area,\n\t\t\t@NotEmpty ValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool(@Negative boolean subZero, @NotBlank boolean saysomething,\n\t\t\t@Pattern(regexp = \"\") Calendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo(@Digits(fraction = 0, integer = 0) boolean x, Integer emailAddress,\n\t\t\t@FutureOrPresent boolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary(@Size double x, @AssertTrue String s, @DecimalMax(\"30.0\") String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams8 = createCodeActionParams(uri, d8);
        TextEdit te8 = te(0, 0, 73, 1, newText8);
        CodeAction ca8 = ca(uri, "Remove constraint annotation Email from element", d8, te8);
        assertJavaCodeAction(codeActionParams8, utils, ca8);

        String newText9 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth(@Past double theGoodOldDays, @Positive String[] area,\n\t\t\t@NotEmpty ValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool(@Negative boolean subZero, @NotBlank boolean saysomething,\n\t\t\t@Pattern(regexp = \"\") Calendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo(@Digits(fraction = 0, integer = 0) boolean x, @Email Integer emailAddress,\n\t\t\tboolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary(@Size double x, @AssertTrue String s, @DecimalMax(\"30.0\") String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams9 = createCodeActionParams(uri, d9);
        TextEdit te9 = te(0, 0, 73, 1, newText9);
        CodeAction ca9 = ca(uri, "Remove constraint annotation FutureOrPresent from element", d9, te9);
        assertJavaCodeAction(codeActionParams9, utils, ca9);

        String newText10 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth(@Past double theGoodOldDays, @Positive String[] area,\n\t\t\t@NotEmpty ValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool(@Negative boolean subZero, @NotBlank boolean saysomething,\n\t\t\t@Pattern(regexp = \"\") Calendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo(@Digits(fraction = 0, integer = 0) boolean x, @Email Integer emailAddress,\n\t\t\t@FutureOrPresent boolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary( double x, @AssertTrue String s, @DecimalMax(\"30.0\") String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams10 = createCodeActionParams(uri, d10);
        TextEdit te10 = te(0, 0, 73, 1, newText10);
        CodeAction ca10 = ca(uri, "Remove constraint annotation Size from element", d10, te10);
        assertJavaCodeAction(codeActionParams10, utils, ca10);

        String newText11 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth(@Past double theGoodOldDays, @Positive String[] area,\n\t\t\t@NotEmpty ValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool(@Negative boolean subZero, @NotBlank boolean saysomething,\n\t\t\t@Pattern(regexp = \"\") Calendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo(@Digits(fraction = 0, integer = 0) boolean x, @Email Integer emailAddress,\n\t\t\t@FutureOrPresent boolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary(@Size double x, String s, @DecimalMax(\"30.0\") String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams11 = createCodeActionParams(uri, d11);
        TextEdit te11 = te(0, 0, 73, 1, newText11);
        CodeAction ca11 = ca(uri, "Remove constraint annotation AssertTrue from element", d11, te11);
        assertJavaCodeAction(codeActionParams11, utils, ca11);

        String newText12 = "package io.openliberty.sample.jakarta.beanvalidation;\n\nimport java.math.BigDecimal;\nimport java.math.BigInteger;\nimport java.util.Calendar;\nimport java.util.Date;\n\nimport jakarta.validation.constraints.AssertFalse;\nimport jakarta.validation.constraints.AssertTrue;\nimport jakarta.validation.constraints.DecimalMax;\nimport jakarta.validation.constraints.Digits;\nimport jakarta.validation.constraints.Email;\nimport jakarta.validation.constraints.FutureOrPresent;\nimport jakarta.validation.constraints.Negative;\nimport jakarta.validation.constraints.NotBlank;\nimport jakarta.validation.constraints.NotEmpty;\nimport jakarta.validation.constraints.Past;\nimport jakarta.validation.constraints.Pattern;\nimport jakarta.validation.constraints.Positive;\nimport jakarta.validation.constraints.Size;\n\npublic class MethodParamConstraintValidation {\n\n\t// valid cases\n\t@AssertTrue\n\tpublic boolean truth(@Past Calendar theGoodOldDays, @Positive float area,\n\t\t\t@NotEmpty ValidConstraints[] validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean boolValid(@Negative int subZero, @NotBlank CharSequence saysomething,\n\t\t\t@Pattern(regexp = \"\") String thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwoValid(@Digits(fraction = 0, integer = 0) BigInteger x, @Email String emailAddress,\n\t\t\t@FutureOrPresent Date graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalaryValid(@Size double[] x, @AssertTrue boolean s,\n\t\t\t@DecimalMax(\"30.0\") BigDecimal bigDecimal) {\n\t\treturn null;\n\t}\n\n\t\n\t// invalid cases\n\t@AssertTrue\n\tpublic boolean anotherTruth(@Past double theGoodOldDays, @Positive String[] area,\n\t\t\t@NotEmpty ValidConstraints validConstraints) {\n\t\treturn true;\n\t}\n\n\t@AssertTrue\n\tpublic Boolean bool(@Negative boolean subZero, @NotBlank boolean saysomething,\n\t\t\t@Pattern(regexp = \"\") Calendar thisIsUsed) {\n\t\treturn false;\n\t}\n\n\t@AssertFalse\n\tprivate boolean boolTwo(@Digits(fraction = 0, integer = 0) boolean x, @Email Integer emailAddress,\n\t\t\t@FutureOrPresent boolean graduationDate) {\n\t\treturn true;\n\t}\n\n\t@Size\n\tprivate double[] getSalary(@Size double x, @AssertTrue String s, String bigDecimal) {\n\t\treturn null;\n\t}\n\n}";
        JakartaJavaCodeActionParams codeActionParams12 = createCodeActionParams(uri, d12);
        TextEdit te12 = te(0, 0, 73, 1, newText12);
        CodeAction ca12 = ca(uri, "Remove constraint annotation DecimalMax from element", d12, te12);
        assertJavaCodeAction(codeActionParams12, utils, ca12);
    }
}