name: Build

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main, lsp4jakarta-0.2.7-release-branch ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.runtime }} - ${{ matrix.test-group }}
    strategy:
      fail-fast: false
      matrix:
        runtime: [ linux, mac, windows ]
        test-group: [ LSP4Jakarta-Unit, Gradle-Jakarta-Language-Server ]
        exclude:
          # Exclude LSP4Jakarta-Unit from mac and windows - only run on linux
          - runtime: mac
            test-group: LSP4Jakarta-Unit
          - runtime: windows
            test-group: LSP4Jakarta-Unit
        include:
          - runtime: linux
            os: ubuntu-latest
          - runtime: mac
            os: macOS-14
          - runtime: windows
            os: windows-latest
          - test-group: Gradle-Jakarta-Language-Server
            test-class: io.openliberty.tools.intellij.it.GradleSingleModJakartaLSTest
          - test-group: LSP4Jakarta-Unit
            test-class: "io.openliberty.tools.intellij.lsp4jakarta.it.*"
    env:
      USE_LOCAL_PLUGIN: false
      TEST_CLASS: ${{ matrix.test-class }}
    steps:
      - name: Configure pagefile
        if: contains(matrix.os, 'windows')
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 8GB
          maximum-size: 10GB
          disk-root: "C:"
      - name: 'Checkout liberty-tools-intellij'
        uses: actions/checkout@v4
        with:
          path: liberty-tools-intellij
      - name: 'Install required integration test software'
        working-directory: ./liberty-tools-intellij
        run: bash ./src/test/resources/ci/scripts/setup.sh

      - name: 'Build Liberty-Tools-Intellij'
        working-directory: ./liberty-tools-intellij
        run: bash ./gradlew buildPlugin

      - name: 'Archive artifacts'
        if: ${{ runner.os == 'Linux' && matrix.test-group == 'LSP4Jakarta-Unit' && !failure() }}
        uses: actions/upload-artifact@v4.3.4
        with:
          name: liberty-tools-intellij-lsp4jakarta
          path: |
            ./**/*liberty-tools-intellij*.zip
            ./**/libs/*liberty-tools-intellij*.jar
          if-no-files-found: warn
          retention-days: 7
      - name: 'Run tests'
        id: run_tests
        working-directory: ./liberty-tools-intellij
        run: bash ./src/test/resources/ci/scripts/run.sh
      - name: 'Archive Test logs and reports'
        if: ${{ failure() && steps.run_tests.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ${{ matrix.runtime }}-${{ matrix.test-group }}-test-report
          path: |
            liberty-tools-intellij/build/reports/
