name: Build

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main, lsp4jakarta-0.2.7-release-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: LSP4Jakarta-Unit

    steps:
      - name: 'Checkout liberty-tools-intellij'
        uses: actions/checkout@v4
        with:
          path: liberty-tools-intellij

      - name: 'Install required integration test software'
        working-directory: ./liberty-tools-intellij
        run: bash ./src/test/resources/ci/scripts/setup.sh

      - name: 'Build Liberty-Tools-Intellij'
        working-directory: ./liberty-tools-intellij
        run: bash ./gradlew buildPlugin

      - name: 'Archive artifacts'
        if: ${{ !failure() }}
        uses: actions/upload-artifact@v4.3.4
        with:
          name: liberty-tools-intellij-lsp4jakarta
          path: |
            ./**/*liberty-tools-intellij*.zip
            ./**/libs/*liberty-tools-intellij*.jar
          if-no-files-found: warn
          retention-days: 7

      - name: 'Run LSP4Jakarta unit tests'
        id: run_tests
        working-directory: ./liberty-tools-intellij
        env:
          TEST_CLASS: "io.openliberty.tools.intellij.lsp4jakarta.it.*"
        run: bash ./src/test/resources/ci/scripts/run.sh

      - name: 'Archive Test logs and reports'
        if: ${{ failure() && steps.run_tests.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4.3.4
        with:
          name: lsp4jakarta-unit-test-report
          path: |
            liberty-tools-intellij/build/reports/
