name: Cron Job

on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    name: Disabled on lsp4jakarta branch
    steps:
      - name: No-op
        run: echo "cronJob is disabled on this branch."
