name: PR - LSP4Jakarta

on:
  pull_request:
    branches: [ 'lsp4jakarta-*-integration*', 'lsp4jakarta-*-release*' ]

jobs:
  call-build:
    uses: ./.github/workflows/build.yaml
    with:
      refLsp4ij: main
      lsp4ijBranch: main
      useLocalPlugin: false
      refLTITag: main
      testGroups: '["LSP4Jakarta-Unit","Gradle-Language-Server","Gradle-MP-Language-Server","Gradle-Jakarta-Language-Server"]'
    secrets: inherit
