name: Fetch All Open and Recently Closed Pull Requests using cron job

on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    name: Disabled on lsp4jakarta branch
    steps:
      - name: No-op
        run: echo "pr-slack-notification is disabled on this branch."
