name: Weekly Build - All OS

on:
  workflow_dispatch:
  schedule:
    # The job runs at 1:30 AM UTC every Monday, which is 7:00 AM IST and 8:30 PM EST (Sunday).
    # Ref - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    - cron: '30 1 * * 1'

jobs:
  # Run the LTI Tests on all OS's against lsp4ij main branch for main and feature branches in progress
  call-build-workflow-all-os:
    uses: ./.github/workflows/build.yaml
    strategy:
      fail-fast: false
      matrix:
        # 'main' plus any feature branches currently in progress.
        # Add or remove branches here as feature work starts or completes.
        tag: [ 'main' , 'lsp4jakarta-0.3.0-integration', 'lsp4jakarta-0.2.7-release-branch', 'lsp4mp-0.17.0-support', 'multi-module-support-feature-branch', 'open-liberty-starter-integration', ]
    with:
      useLocalPlugin: false
      refLsp4ij: main
      lsp4ijBranch: main
      refLTITag: ${{ matrix.tag }}
      allOS: true
    name: Weekly All-OS Build
